package pgxaip_test

import (
	"context"
	"fmt"
	"os"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/pgx-contrib/pgxaip"
	"go.einride.tech/aip/filtering"
	"go.einride.tech/aip/ordering"
)

func ExampleChainRewriter() {
	config, err := pgxpool.ParseConfig(os.Getenv("PGX_DATABASE_URL"))
	if err != nil {
		panic(err)
	}
	pool, err := pgxpool.NewWithConfig(context.TODO(), config)
	if err != nil {
		panic(err)
	}
	defer pool.Close()

	declarations, err := filtering.NewDeclarations(
		filtering.DeclareStandardFunctions(),
		filtering.DeclareIdent("display_name", filtering.TypeString),
		filtering.DeclareIdent("collection_id", filtering.TypeString),
	)
	if err != nil {
		panic(err)
	}

	filter, err := filtering.ParseFilterString(`display_name = "Photos"`, declarations)
	if err != nil {
		panic(err)
	}

	var orderBy ordering.OrderBy
	if err := orderBy.UnmarshalString("display_name desc"); err != nil {
		panic(err)
	}

	// Effective ordering = user fields + SQL-level fallback (collection_id).
	effective := append([]ordering.Field{}, orderBy.Fields...)
	effective = append(effective, ordering.Field{Path: "collection_id"})

	// AIP path -> DB column. In a real app these come from the
	// `*FilterColumns` / `*OrderByColumns` maps generated by
	// protoc-gen-go-aip-query.
	filterCols := map[string]string{
		"display_name":  "display_name",
		"collection_id": "collection_id",
	}
	orderCols := map[string]string{
		"display_name":  "display_name",
		"collection_id": "collection_id",
	}

	chain := pgxaip.ChainRewriter{
		&pgxaip.FilterRewriter{Filter: filter, Columns: filterCols},
		&pgxaip.OrderByRewriter{OrderBy: orderBy, Columns: orderCols},
		&pgxaip.CursorRewriter{Fields: effective, Values: nil /* first page */, Columns: orderCols},
	}

	const sql = `
		SELECT * FROM collection
		WHERE /* query.cursor AND */ TRUE
		  AND /* query.filter AND */ TRUE
		ORDER BY /* query.order , */ collection_id
		LIMIT $1::int OFFSET $2::int`

	rows, err := pool.Query(context.TODO(), sql, chain, int32(20), int32(0))
	if err != nil {
		panic(err)
	}
	defer rows.Close()

	fmt.Println("ok")
}
